import cadquery as cq
w0=cq.Workplane('YZ',origin=(23,0,0))
w1=cq.Workplane('XY',origin=(0,0,-17))
r=w0.sketch().push([(-45,0.5)]).rect(60,53).push([(43,-68)]).circle(32).finalize().extrude(-99).union(w0.sketch().segment((-67,32),(-38,32)).segment((-38,21)).segment((-26,21)).segment((-26,32)).segment((3,32)).segment((3,90)).segment((-26,90)).segment((-26,100)).segment((-38,100)).segment((-38,90)).segment((-67,90)).close().assemble().finalize().extrude(53)).union(w1.sketch().segment((-26,-50),(43,-50)).segment((43,-40)).segment((17,-40)).arc((5,-32),(-7,-40)).segment((-26,-40)).close().assemble().finalize().extrude(24))