import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-40))
r=w0.sketch().arc((-78,39),(-79,32),(-76,25)).segment((-75,17)).segment((-57,20)).segment((-58,28)).arc((-56,35),(-60,42)).segment((-61,50)).segment((-75,48)).arc((29,-14),(-78,41)).close().assemble().finalize().extrude(74).union(w0.sketch().segment((-82,-64),(-68,-64)).segment((-68,-84)).segment((-7,-84)).segment((-7,-92)).segment((24,-92)).segment((24,-84)).segment((86,-84)).segment((86,-64)).segment((100,-64)).segment((100,15)).segment((86,15)).segment((86,35)).segment((50,35)).arc((-59,83),(-82,-34)).close().assemble().finalize().extrude(80))