import cadquery as cq
w0=cq.Workplane('YZ',origin=(-43,0,0))
r=w0.workplane(offset=-8/2).moveTo(-48,-65).cylinder(8,30).union(w0.sketch().segment((-21,92),(-5,53)).segment((-13,-22)).segment((91,-33)).segment((100,52)).segment((-1,63)).segment((-14,95)).close().assemble().finalize().extrude(26)).union(w0.sketch().segment((-100,-7),(-98,-7)).segment((-98,-18)).segment((-69,-18)).segment((-69,-24)).segment((-41,-24)).segment((-41,-34)).segment((10,-34)).segment((10,-24)).segment((38,-24)).segment((38,-1)).segment((10,-1)).segment((10,9)).segment((-21,9)).segment((-21,11)).segment((-24,11)).segment((-24,22)).segment((-98,22)).segment((-98,11)).segment((-100,11)).close().assemble().finalize().extrude(95))