import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,37))
w1=cq.Workplane('ZX',origin=(0,24,0))
r=w0.sketch().segment((-100,-49),(-76,-49)).segment((-76,-62)).segment((-58,-62)).segment((-58,-49)).segment((-35,-49)).segment((-35,-17)).segment((-34,-15)).segment((-35,-15)).segment((-35,9)).segment((-58,9)).segment((-58,22)).segment((-76,22)).segment((-76,9)).segment((-100,9)).segment((-100,-23)).segment((-100,-25)).close().assemble().push([(-67,-20)]).circle(4,mode='s').finalize().extrude(-79).union(w0.sketch().arc((34,4),(82,-11),(95,37)).arc((90,39),(86,42)).segment((83,42)).arc((76,1),(34,4)).assemble().finalize().extrude(-62)).union(w1.sketch().segment((6,15),(22,15)).segment((42,15)).segment((42,18)).segment((6,18)).close().assemble().finalize().extrude(38))