import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,-3,0))
w1=cq.Workplane('XY',origin=(0,0,70))
r=w0.sketch().segment((-100,45),(-29,45)).arc((95,5),(-21,65)).segment((-100,65)).close().assemble().push([(-51,55)]).circle(8,mode='s').push([(34.5,29)]).rect(11,68,mode='s').finalize().extrude(-38).union(w1.sketch().segment((-95,-28),(-76,-28)).segment((-76,-48)).segment((-21,-48)).segment((-21,-28)).segment((-1,-28)).segment((-1,-24)).segment((-21,-24)).segment((-21,2)).segment((24,2)).segment((24,26)).segment((-21,26)).segment((-21,48)).segment((-76,48)).segment((-76,26)).segment((-95,26)).close().assemble().finalize().extrude(12))