import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,42,0))
r=w0.sketch().push([(-51,-42)]).circle(47).reset().face(w0.sketch().segment((-74,-64),(-72,-64)).arc((-51,-72),(-31,-64)).segment((-29,-64)).segment((-29,-62)).arc((-21,-42),(-29,-21)).segment((-29,-19)).segment((-31,-19)).arc((-51,-11),(-72,-19)).segment((-74,-19)).segment((-74,-21)).arc((-82,-42),(-74,-62)).close().assemble(),mode='s').finalize().extrude(-84).union(w0.sketch().push([(47,48)]).circle(52).reset().face(w0.sketch().segment((14,25),(66,12)).segment((74,33)).segment((68,36)).segment((70,39)).segment((71,38)).segment((72,40)).segment((69,42)).segment((71,50)).segment((64,51)).segment((47,91)).segment((16,79)).segment((25,56)).segment((21,57)).close().assemble(),mode='s').finalize().extrude(-78)).union(w0.sketch().push([(-49.5,-62)]).rect(51,76).push([(-49,-62)]).circle(3,mode='s').finalize().extrude(-53))