import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,66,0))
r=w0.sketch().segment((-48,-6),(-17,-6)).arc((2,-10),(22,-6)).segment((53,-6)).segment((53,73)).segment((22,73)).arc((2,77),(-17,73)).segment((-48,73)).close().assemble().finalize().extrude(-132).union(w0.sketch().segment((67,-77),(79,-77)).segment((79,-63)).arc((74,-63),(69,-62)).segment((78,-42)).segment((79,-43)).segment((79,-40)).segment((75,-40)).segment((67,-33)).close().assemble().reset().face(w0.sketch().segment((67,-30),(72,-30)).segment((79,-37)).segment((79,-30)).segment((73,-30)).segment((67,-10)).close().assemble()).finalize().extrude(-132)).union(w0.sketch().push([(-51,-46)]).rect(98,32).push([(73,-37)]).circle(27).circle(14,mode='s').finalize().extrude(-72))