import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-41))
w1=cq.Workplane('ZX',origin=(0,-17,0))
r=w0.sketch().segment((1,8),(12,8)).arc((30,-6),(50,8)).segment((60,8)).segment((60,12)).segment((55,12)).arc((30,30),(5,12)).segment((1,12)).close().assemble().reset().face(w0.sketch().segment((6,12),(13,12)).arc((10,13),(6,12)).assemble(),mode='s').reset().face(w0.sketch().arc((6,8),(10,7),(13,8)).close().assemble(),mode='s').reset().face(w0.sketch().segment((6,12),(13,12)).arc((10,13),(6,12)).assemble(),mode='s').reset().face(w0.sketch().segment((6,12),(12,12)).arc((10,13),(6,12)).assemble(),mode='s').reset().face(w0.sketch().arc((6,8),(10,7),(13,8)).close().assemble(),mode='s').finalize().extrude(-39).union(w0.sketch().segment((1,32),(11,23)).segment((11,22)).segment((60,62)).segment((60,100)).segment((1,100)).close().assemble().finalize().extrude(-39)).union(w1.sketch().segment((-11,-60),(80,-60)).segment((80,23)).segment((11,23)).arc((-17,28),(-11,-5)).close().assemble().push([(34,-20)]).circle(32,mode='s').finalize().extrude(-83))