import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,-20,0))
r=w0.sketch().segment((13,-56),(21,-56)).arc((29,-90),(63,-97)).segment((58,-97)).segment((58,-94)).segment((66,-94)).segment((66,-92)).segment((68,-92)).segment((68,-93)).arc((73,-84),(77,-78)).segment((71,-78)).arc((63,-80),(58,-74)).segment((58,-78)).segment((51,-78)).segment((51,-76)).segment((47,-76)).segment((47,-78)).segment((17,-78)).segment((17,-56)).segment((51,-56)).segment((51,-58)).segment((68,-58)).segment((68,-56)).segment((71,-56)).arc((49,-39),(21,-45)).segment((13,-45)).close().assemble().finalize().extrude(36).union(w0.sketch().segment((-78,16),(12,16)).segment((12,62)).segment((17,62)).segment((17,100)).segment((-65,100)).segment((-65,92)).segment((-78,92)).close().assemble().reset().face(w0.sketch().segment((-63,62),(-63,63)).arc((-3,36),(-61,66)).segment((-61,62)).close().assemble(),mode='s').finalize().extrude(40))