import cadquery as cq
w0=cq.Workplane('YZ',origin=(-26,0,0))
r=w0.sketch().segment((-22,66),(-21,-12)).segment((-1,-12)).segment((-1,-22)).segment((14,-22)).arc((34,-29),(54,-22)).segment((57,-22)).segment((57,-33)).arc((60,-27),(61,-22)).segment((66,-22)).segment((66,-12)).segment((79,-12)).segment((79,66)).segment((74,66)).segment((74,76)).segment((61,76)).arc((41,81),(21,80)).segment((20,86)).segment((-1,86)).segment((-1,76)).segment((-2,76)).segment((-2,66)).close().assemble().push([(29,27)]).rect(58,90,mode='s').finalize().extrude(-74).union(w0.sketch().arc((-72,4),(-76,-43),(-48,-79)).segment((-48,-81)).segment((-45,-81)).arc((-16,-88),(13,-81)).segment((17,-81)).segment((17,-79)).arc((47,-35),(28,19)).segment((28,21)).segment((26,21)).arc((-15,38),(-57,23)).segment((-72,23)).close().assemble().reset().face(w0.sketch().arc((-30,-22),(-15,-38),(0,-22)).close().assemble(),mode='s').finalize().extrude(126))