import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-17))
w1=cq.Workplane('ZX',origin=(0,36,0))
r=w0.sketch().push([(48,-58)]).circle(42).push([(47.5,-58.5)]).rect(71,15,mode='s').finalize().extrude(-17).union(w0.sketch().segment((-86,-2),(-50,-2)).segment((-71,-32)).segment((-41,-53)).segment((-6,-4)).segment((-36,18)).segment((-45,5)).segment((-86,5)).close().assemble().reset().face(w0.sketch().segment((-53,-25),(-24,-25)).segment((-24,-10)).segment((-53,-10)).segment((-53,-13)).segment((-52,-13)).segment((-52,-22)).segment((-53,-22)).close().assemble(),mode='s').finalize().extrude(41)).union(w1.workplane(offset=64/2).moveTo(30,-63).box(8,54,64))