import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,76,0))
r=w0.sketch().segment((-90,1),(-89,1)).segment((-89,-30)).segment((6,-30)).arc((65,-96),(39,-17)).segment((39,10)).arc((2,-18),(-42,-20)).segment((-44,-21)).segment((-45,-20)).arc((-73,-7),(-89,19)).segment((-89,12)).arc((-88,10),(-89,7)).segment((-89,6)).segment((-90,5)).close().assemble().finalize().extrude(-173).union(w0.sketch().push([(-25,57)]).circle(14).circle(12,mode='s').finalize().extrude(-153)).union(w0.sketch().segment((-84,25),(-23,-15)).segment((5,20)).segment((5,16)).segment((15,16)).segment((15,29)).segment((51,79)).segment((31,94)).segment((31,100)).segment((25,100)).segment((25,98)).segment((23,99)).segment((15,99)).segment((15,100)).segment((5,100)).segment((5,77)).segment((-6,63)).segment((-6,57)).segment((-12,57)).close().assemble().finalize().extrude(21))