import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,3))
r=w0.sketch().arc((4,18),(36,8),(58,37)).arc((12,95),(4,18)).assemble().finalize().extrude(-90).union(w0.sketch().segment((-73,-100),(-36,-100)).segment((-36,-93)).arc((-54,-95),(-73,-93)).close().assemble().finalize().extrude(36)).union(w0.sketch().segment((-39,23),(-32,14)).arc((-75,-62),(0,-21)).segment((89,52)).segment((49,100)).close().assemble().reset().face(w0.sketch().segment((-74,-5),(-72,-14)).segment((-52,-7)).segment((-54,1)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-44,-51),(-38,-51)).arc((-30,-55),(-22,-51)).segment((-16,-51)).segment((-16,-49)).segment((-22,-49)).arc((-30,-44),(-38,-49)).segment((-44,-49)).close().assemble(),mode='s').push([(-30,-50)]).circle(2,mode='s').finalize().extrude(84))