import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,41))
r=w0.sketch().segment((-42,22),(-38,22)).segment((-38,27)).segment((31,27)).segment((31,22)).segment((40,22)).segment((40,100)).segment((-42,100)).close().assemble().push([(-1,61.5)]).rect(2,39,mode='s').finalize().extrude(-83).union(w0.sketch().push([(-67.5,-97)]).rect(43,6).reset().face(w0.sketch().segment((-47,-21),(13,-96)).segment((13,-62)).segment((19,-62)).segment((19,-90)).segment((14,-90)).segment((14,-97)).segment((89,-38)).segment((40,27)).segment((32,21)).segment((32,6)).segment((29,6)).segment((29,19)).segment((13,1)).segment((13,27)).segment((-23,27)).segment((-23,1)).segment((-26,1)).segment((-26,6)).segment((-29,6)).segment((-29,-6)).close().assemble()).push([(20.5,-30)]).rect(87,32,mode='s').finalize().extrude(-33))