import cadquery as cq
w0=cq.Workplane('YZ',origin=(-33,0,0))
w1=cq.Workplane('XY',origin=(0,0,-10))
r=w0.sketch().segment((-18,-82),(3,-82)).segment((3,-75)).arc((10,-62),(3,-50)).segment((3,-43)).segment((-18,-43)).segment((-18,-50)).arc((-24,-62),(-18,-75)).close().assemble().finalize().extrude(-43).union(w0.sketch().push([(-81,-48)]).circle(19).reset().face(w0.sketch().segment((17,74),(26,59)).segment((19,29)).segment((25,28)).segment((33,46)).segment((48,-8)).segment((100,36)).segment((68,73)).segment((49,55)).segment((32,82)).close().assemble()).finalize().extrude(43)).union(w1.sketch().segment((25,-26),(27,-26)).arc((28,-24),(29,-26)).segment((32,-26)).segment((32,32)).segment((76,32)).segment((76,65)).segment((9,65)).segment((9,32)).segment((25,32)).close().assemble().finalize().extrude(-71))