import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,-84,0))
w1=cq.Workplane('ZX',origin=(0,-24,0))
r=w0.sketch().segment((-41,31),(-40,30)).arc((-28,16),(-11,12)).segment((-10,11)).segment((-9,12)).arc((24,21),(38,52)).segment((39,53)).segment((38,54)).arc((26,81),(1,96)).segment((0,97)).segment((-1,97)).arc((-35,84),(-40,46)).segment((-41,45)).segment((-40,44)).arc((-40,37),(-38,32)).close().assemble().reset().face(w0.sketch().segment((33,-11),(44,-34)).segment((57,-10)).segment((78,-10)).segment((78,-8)).segment((58,-8)).segment((77,3)).segment((72,10)).segment((75,36)).close().assemble()).reset().face(w0.sketch().segment((62,-47),(63,-48)).segment((75,-48)).segment((75,-59)).segment((82,-59)).segment((82,-67)).segment((75,-67)).segment((75,-69)).segment((100,-68)).arc((82,-52),(80,-27)).segment((79,-19)).segment((78,-19)).segment((78,-10)).segment((62,-10)).close().assemble()).finalize().extrude(88).union(w0.workplane(offset=88/2).moveTo(-5,54).cylinder(88,43)).union(w1.sketch().arc((-80,28),(-18,-91),(15,34)).arc((-29,13),(-80,28)).assemble().finalize().extrude(108))