import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,37,0))
w1=cq.Workplane('XY',origin=(0,0,2))
r=w0.sketch().segment((-79,-38),(-16,-92)).segment((80,5)).segment((61,23)).arc((-23,-12),(-14,88)).segment((-16,92)).segment((-17,91)).segment((-17,100)).segment((-28,92)).segment((-22,85)).arc((-70,42),(-61,-20)).close().assemble().finalize().extrude(-5).union(w0.sketch().segment((-80,-25),(-30,-25)).segment((-30,-26)).segment((-26,-25)).segment((-17,-25)).segment((-17,-23)).segment((-16,-23)).segment((-16,-25)).segment((-14,-25)).segment((-14,-27)).segment((31,-22)).segment((31,9)).segment((44,9)).segment((44,-21)).segment((46,-20)).segment((37,9)).segment((44,9)).segment((44,2)).segment((46,2)).segment((46,9)).segment((31,9)).segment((31,46)).segment((-80,46)).close().assemble().finalize().extrude(12)).union(w1.sketch().arc((-86,-20),(-96,-45),(-70,-39)).segment((-64,-39)).segment((-64,31)).segment((-86,31)).close().assemble().finalize().extrude(-15))