import cadquery as cq
w0=cq.Workplane('YZ',origin=(-19,0,0))
r=w0.sketch().segment((-22,-20),(-11,-20)).segment((-11,-30)).arc((4,5),(-22,-20)).assemble().push([(4,-10)]).circle(7,mode='s').finalize().extrude(-51).union(w0.sketch().segment((-100,-46),(-88,-62)).segment((-89,-61)).segment((-94,-65)).segment((-89,-72)).segment((-89,-82)).segment((-82,-82)).segment((-82,-77)).segment((-80,-78)).segment((-80,-80)).segment((-84,-84)).segment((-82,-85)).segment((-81,-80)).segment((-81,-79)).segment((-80,-78)).segment((-81,-78)).segment((-74,-54)).segment((-62,-60)).segment((-46,-40)).segment((-49,-38)).segment((-34,-17)).segment((-66,13)).segment((-72,4)).segment((-57,-14)).close().assemble().finalize().extrude(53)).union(w0.sketch().segment((-50,-1),(-26,-26)).segment((-21,-20)).segment((-21,-18)).segment((16,-18)).segment((16,-2)).segment((0,-2)).segment((36,32)).arc((99,58),(31,48)).segment((17,63)).close().assemble().push([(8,-10)]).circle(8,mode='s').finalize().extrude(90))