import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,20))
r=w0.sketch().push([(-16,76)]).circle(21).reset().face(w0.sketch().segment((3,-17),(13,-17)).segment((13,74)).segment((11,74)).segment((11,72)).segment((3,72)).close().assemble()).push([(66,-5)]).circle(34).reset().face(w0.sketch().segment((35,11),(41,-6)).segment((41,-14)).segment((44,-14)).segment((51,-31)).segment((67,-25)).segment((71,-31)).segment((82,-25)).segment((76,-14)).segment((91,-14)).segment((91,-4)).segment((84,-4)).segment((81,4)).segment((83,17)).segment((74,18)).segment((72,19)).segment((71,19)).segment((57,17)).segment((53,23)).segment((42,18)).segment((48,-4)).segment((34,-4)).segment((34,-5)).segment((47,-5)).segment((47,-3)).segment((35,-3)).close().assemble(),mode='s').finalize().extrude(-62).union(w0.sketch().segment((-100,-52),(-69,-52)).segment((-69,-97)).segment((14,-97)).segment((14,-13)).segment((-38,-13)).segment((-38,-5)).segment((-100,-5)).close().assemble().push([(-68,-24)]).circle(6,mode='s').reset().face(w0.sketch().segment((-69,-79),(-69,-52)).arc((-73,-66),(-69,-79)).assemble(),mode='s').finalize().extrude(22))