import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-80))
r=w0.sketch().segment((-97,20),(-64,20)).arc((-30,5),(3,20)).segment((21,20)).arc((36,-100),(51,20)).segment((58,20)).segment((58,33)).segment((13,33)).arc((-30,100),(-73,33)).segment((-97,33)).close().assemble().reset().face(w0.sketch().segment((-41,20),(-40,19)).segment((-35,20)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-41,33),(-29,33)).segment((-29,35)).segment((-34,35)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-41,35),(-36,35)).segment((-36,36)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-26,17),(-6,18)).segment((-6,20)).segment((-26,19)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-26,35),(1,35)).segment((1,36)).segment((-26,36)).close().assemble(),mode='s').finalize().extrude(160)