import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,-51,0))
r=w0.sketch().segment((-80,-25),(-68,-35)).segment((-68,-37)).segment((-66,-37)).segment((-59,-43)).segment((-54,-37)).segment((-38,-37)).segment((-38,-46)).segment((-29,-46)).segment((-29,-43)).segment((6,-43)).segment((6,-46)).segment((13,-46)).segment((13,-43)).segment((25,-43)).segment((25,-4)).segment((41,15)).segment((25,27)).segment((25,29)).segment((23,29)).segment((13,36)).segment((13,38)).segment((11,38)).segment((6,42)).segment((6,43)).segment((4,43)).segment((-3,49)).segment((-8,43)).segment((-11,43)).arc((-76,92),(-69,9)).segment((-69,0)).segment((-74,0)).segment((-74,-1)).segment((-69,-1)).segment((-69,-6)).segment((-74,-6)).segment((-74,-10)).segment((-69,-10)).segment((-69,-13)).segment((-74,-13)).segment((-74,-17)).segment((-79,-17)).close().assemble().finalize().extrude(67).union(w0.workplane(offset=102/2).moveTo(40.5,-38.5).box(119,117,102))