import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,49,0))
r=w0.workplane(offset=-136/2).moveTo(-13.5,48).box(5,50,136).union(w0.sketch().segment((-81,19),(-57,19)).arc((-14,-3),(29,19)).segment((35,19)).segment((35,31)).arc((-6,100),(-64,42)).segment((-81,42)).close().assemble().reset().face(w0.sketch().arc((-34,19),(-24,15),(-12,19)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-34,42),(-12,42)).arc((-24,47),(-34,42)).assemble(),mode='s').finalize().extrude(-89)).union(w0.sketch().segment((56,-54),(75,-100)).arc((80,-61),(67,-26)).segment((66,-27)).segment((66,-28)).arc((62,-40),(56,-54)).assemble().finalize().extrude(38))