import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-9))
r=w0.sketch().segment((5,-24),(9,-24)).segment((9,-47)).segment((27,-47)).arc((30,-53),(35,-50)).arc((51,-47),(51,-31)).segment((51,-24)).segment((55,-24)).segment((55,-23)).segment((51,-23)).segment((100,7)).segment((65,56)).segment((12,18)).segment((24,0)).arc((26,-1),(27,-3)).segment((9,-3)).segment((9,-23)).segment((5,-23)).close().assemble().push([(56.5,11)]).rect(79,16,mode='s').finalize().extrude(1).union(w0.sketch().segment((-100,-49),(-39,-56)).segment((-32,13)).segment((-93,19)).close().assemble().reset().face(w0.sketch().segment((-89,-14),(-86,-14)).segment((-86,-11)).segment((-59,-11)).segment((-59,-14)).segment((-56,-14)).arc((-67,-11),(-79,-13)).arc((-82,-13),(-85,-11)).segment((-89,-11)).close().assemble(),mode='s').reset().face(w0.sketch().arc((-70,-24),(-63,-25),(-57,-24)).close().assemble(),mode='s').finalize().extrude(18))