import cadquery as cq
w0=cq.Workplane('YZ',origin=(-19,0,0))
w1=cq.Workplane('YZ',origin=(-20,0,0))
r=w0.sketch().segment((-28,-5),(-18,-5)).segment((-19,-27)).segment((-6,-27)).segment((-6,-5)).segment((3,-5)).segment((3,-1)).segment((0,-1)).segment((0,1)).segment((3,1)).segment((3,3)).arc((-10,10),(-18,-1)).segment((-28,-1)).close().assemble().finalize().extrude(-52).union(w0.sketch().segment((-100,-46),(-87,-62)).segment((-94,-81)).segment((-83,-84)).segment((-78,-69)).segment((-60,-59)).segment((-60,-58)).segment((-58,-58)).segment((-46,-49)).segment((-59,-33)).segment((-51,-15)).segment((-62,-13)).segment((-67,-28)).close().assemble().push([(-60,-44)]).circle(15,mode='s').finalize().extrude(53)).union(w0.sketch().segment((-50,-2),(-24,-25)).segment((-17,-18)).segment((16,-18)).segment((16,-2)).segment((-1,-2)).segment((38,30)).segment((38,29)).arc((98,61),(31,48)).segment((16,63)).close().assemble().finalize().extrude(90)).union(w1.sketch().push([(-8,-10)]).circle(20).circle(11,mode='s').finalize().extrude(-48))