import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,37,0))
w1=cq.Workplane('XY',origin=(0,0,-13))
r=w0.sketch().segment((-80,27),(-57,14)).arc((-56,-59),(16,-62)).segment((21,-65)).segment((80,4)).segment((57,26)).arc((1,-11),(-54,28)).segment((-42,28)).segment((-47,69)).segment((-29,71)).arc((-23,76),(-16,81)).segment((-16,100)).segment((-26,100)).segment((-26,85)).segment((-31,86)).close().assemble().finalize().extrude(-5).union(w0.sketch().push([(-24.5,10.5)]).rect(111,71).reset().face(w0.sketch().segment((-47,23),(-45,18)).segment((-45,13)).segment((-43,13)).segment((-37,4)).segment((-19,13)).segment((-16,13)).segment((-16,14)).segment((-13,16)).segment((-16,21)).segment((-16,26)).segment((-18,26)).segment((-24,35)).segment((-43,26)).segment((-45,26)).segment((-45,25)).segment((-45,24)).close().assemble(),mode='s').finalize().extrude(12)).union(w1.sketch().arc((-95,-24),(-92,-48),(-72,-42)).segment((-64,-42)).segment((-64,29)).segment((-75,29)).segment((-75,-2)).segment((-85,-2)).segment((-85,27)).segment((-95,27)).close().assemble().finalize().extrude(15))