import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,-17,0))
w1=cq.Workplane('ZX',origin=(0,-7,0))
r=w0.sketch().segment((-100,38),(-99,38)).segment((-99,37)).segment((-95,38)).segment((-47,38)).segment((-47,-4)).segment((10,-4)).segment((10,86)).segment((-47,86)).segment((-47,60)).segment((-52,60)).segment((-52,61)).segment((-57,60)).segment((-99,60)).segment((-99,51)).segment((-100,51)).close().assemble().reset().face(w0.sketch().arc((-63,51),(-55,47),(-47,51)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-63,51),(-47,51)).arc((-55,55),(-63,51)).assemble(),mode='s').finalize().extrude(-53).union(w0.workplane(offset=-14/2).moveTo(-10,-53).cylinder(14,3)).union(w1.sketch().segment((63,-86),(100,-86)).segment((100,-74)).arc((81,-81),(63,-74)).close().assemble().finalize().extrude(77))