import cadquery as cq
w0=cq.Workplane('YZ',origin=(11,0,0))
r=w0.sketch().segment((-11,-100),(11,-100)).segment((11,-57)).arc((58,0),(11,57)).segment((11,100)).segment((-11,100)).segment((-11,57)).arc((-58,0),(-11,-57)).close().assemble().reset().face(w0.sketch().segment((-48,-29),(-38,-29)).arc((-37,-33),(-35,-36)).segment((-38,-37)).segment((-35,-48)).segment((-23,-45)).segment((-24,-50)).segment((-14,-52)).segment((-12,-52)).segment((-11,-52)).segment((-11,-51)).segment((-7,-52)).segment((-7,-49)).arc((13,-40),(17,-19)).segment((22,-19)).segment((20,-8)).segment((19,-8)).segment((19,14)).segment((-15,14)).segment((-33,25)).segment((-39,14)).segment((-39,11)).segment((-48,11)).close().assemble(),mode='s').reset().face(w0.sketch().segment((13,14),(15,14)).segment((15,13)).segment((19,-11)).segment((19,14)).segment((39,14)).segment((39,19)).segment((35,19)).segment((36,24)).segment((27,26)).segment((24,19)).segment((13,19)).close().assemble(),mode='s').finalize().extrude(-22)