import cadquery as cq
w0=cq.Workplane('YZ',origin=(-11,0,0))
w1=cq.Workplane('ZX',origin=(0,32,0))
r=w0.sketch().segment((-37,49),(-37,68)).arc((-83,-15),(-10,45)).segment((-10,49)).close().assemble().push([(63,-33)]).circle(37).circle(31,mode='s').finalize().extrude(-71).union(w0.sketch().segment((-49,17),(-42,17)).segment((-42,14)).segment((-48,14)).arc((-44,12),(-39,11)).arc((-34,10),(-29,11)).arc((-25,49),(-49,17)).assemble().finalize().extrude(18)).union(w0.workplane(offset=93/2).moveTo(42,-20.5).box(2,7,93)).union(w1.sketch().segment((-62,-52),(23,-52)).segment((23,-32)).segment((-23,-32)).segment((-23,-25)).segment((23,-25)).segment((23,-31)).segment((25,-31)).segment((25,-32)).segment((26,-32)).segment((26,-37)).segment((25,-37)).segment((25,-45)).segment((23,-45)).segment((23,-37)).segment((-23,-37)).segment((-23,-32)).segment((-25,-32)).segment((-25,-30)).segment((-23,-30)).segment((-23,-25)).segment((-23,-23)).segment((-23,-20)).segment((-26,-20)).segment((-26,-23)).segment((-62,-23)).close().assemble().finalize().extrude(-15))