import cadquery as cq
w0=cq.Workplane('YZ',origin=(1,0,0))
r=w0.sketch().segment((-15,-5),(56,-5)).segment((56,29)).arc((61,48),(56,66)).segment((56,100)).segment((-12,100)).segment((-12,66)).arc((-17,48),(-15,29)).close().assemble().push([(-12.5,-64.5)]).rect(5,31).finalize().extrude(-41).union(w0.sketch().push([(-27,-5.5)]).rect(104,103).push([(-27,-5)]).circle(36,mode='s').finalize().extrude(-20)).union(w0.sketch().segment((-23,-52),(-7,-100)).segment((25,-88)).segment((45,-88)).segment((45,-80)).segment((53,-78)).segment((50,-68)).segment((52,-69)).segment((79,-7)).segment((38,10)).segment((19,-38)).segment((14,-37)).segment((14,-41)).segment((11,-41)).segment((11,-37)).segment((2,-42)).segment((-1,-41)).segment((-1,-39)).close().assemble().push([(9,-69)]).circle(2,mode='s').finalize().extrude(39))