import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,74,0))
r=w0.sketch().segment((-91,-17),(20,-31)).segment((22,-22)).segment((76,-48)).segment((91,-14)).segment((26,14)).segment((28,24)).segment((7,28)).segment((12,93)).segment((-84,100)).close().assemble().push([(-40,39)]).rect(6,118,mode='s').finalize().extrude(-148).union(w0.sketch().segment((-61,-27),(2,-100)).segment((18,-87)).segment((18,-74)).segment((32,-74)).segment((59,-52)).segment((59,-50)).segment((62,-50)).segment((81,-37)).segment((77,-31)).segment((80,-27)).segment((63,-18)).segment((59,-11)).segment((59,-7)).segment((56,-7)).segment((39,10)).segment((35,15)).segment((35,16)).segment((33,16)).segment((-6,58)).segment((-48,16)).segment((-53,16)).segment((-53,11)).segment((-60,4)).segment((-57,0)).segment((-59,-2)).segment((-56,-4)).segment((-54,-7)).segment((-52,-7)).close().assemble().finalize().extrude(-130))