import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,49))
r=w0.sketch().segment((-86,-63),(-25,-63)).segment((-25,-50)).arc((-20,-44),(-17,-38)).arc((44,32),(-52,28)).segment((-86,28)).segment((-86,15)).arc((-100,-18),(-86,-50)).close().assemble().reset().face(w0.sketch().arc((-28,28),(-19,8),(-11,-14)).segment((-11,-18)).segment((-7,-18)).arc((5,-17),(17,-11)).segment((20,-11)).segment((20,-7)).arc((27,11),(21,29)).segment((21,32)).segment((18,32)).arc((5,40),(-10,41)).segment((-14,41)).segment((-14,39)).arc((-21,35),(-28,29)).close().assemble(),mode='s').finalize().extrude(-98).union(w0.sketch().segment((-43,24),(-37,24)).arc((0,42),(37,24)).segment((43,24)).arc((0,44),(-43,24)).assemble().finalize().extrude(-36)).union(w0.workplane(offset=-37/2).moveTo(75.5,50).box(49,12,37))