import cadquery as cq
w0=cq.Workplane('YZ',origin=(-23,0,0))
r=w0.sketch().arc((-63,-2),(-98,-59),(-35,-78)).segment((-36,-78)).segment((-36,-76)).segment((-34,-76)).arc((-30,-73),(-27,-69)).segment((-17,-48)).segment((-5,-53)).segment((-5,-67)).segment((-9,-67)).segment((-9,-82)).segment((3,-82)).segment((3,-65)).segment((21,-8)).segment((13,-5)).segment((21,21)).segment((-45,45)).close().assemble().push([(68.5,41)]).rect(63,82).finalize().extrude(21).union(w0.sketch().segment((-47,-14),(-33,-34)).segment((-12,-18)).segment((-33,-18)).segment((-33,-12)).segment((-16,-12)).segment((-16,-17)).segment((-9,-12)).segment((-14,-4)).segment((-3,-4)).segment((-3,-10)).segment((16,-8)).segment((4,33)).segment((-28,26)).segment((-26,19)).segment((-33,19)).segment((-33,14)).segment((-43,14)).segment((-37,-4)).close().assemble().push([(-34,58)]).circle(28).finalize().extrude(46))