import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,40))
r=w0.workplane(offset=-80/2).moveTo(-58.5,45.5).box(83,95,80).union(w0.sketch().arc((11,66),(-37,35),(17,15)).segment((19,15)).segment((19,17)).arc((23,20),(26,25)).segment((33,23)).segment((35,31)).segment((32,31)).arc((32,39),(30,47)).segment((34,47)).segment((34,26)).segment((36,26)).segment((36,47)).segment((37,47)).segment((37,26)).segment((38,26)).segment((38,25)).arc((39,33),(38,40)).segment((38,44)).segment((34,44)).segment((34,63)).segment((30,63)).segment((30,44)).segment((29,44)).segment((29,63)).segment((28,63)).segment((28,62)).arc((27,63),(25,63)).segment((11,63)).close().assemble().push([(54.5,-52.5)]).rect(91,81).finalize().extrude(-39)).union(w0.workplane(offset=-4/2).moveTo(-4,35).cylinder(4,31))