import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,13))
w1=cq.Workplane('YZ',origin=(-39,0,0))
r=w0.sketch().segment((-75,-25),(-57,-25)).segment((-57,-88)).segment((27,-88)).segment((27,-22)).arc((70,9),(34,41)).arc((31,53),(27,63)).segment((27,82)).segment((3,82)).arc((-24,88),(-50,82)).segment((-75,82)).segment((-75,59)).arc((-83,28),(-75,-2)).close().assemble().reset().face(w0.sketch().segment((-38,-75),(7,-75)).segment((7,-52)).arc((-15,-60),(-38,-52)).close().assemble(),mode='s').finalize().extrude(-113).union(w0.workplane(offset=87/2).moveTo(-24,28).cylinder(87,8)).union(w1.sketch().arc((1,17),(22,17),(27,2)).arc((39,64),(1,17)).assemble().finalize().extrude(122))