import cadquery as cq
w0=cq.Workplane('YZ',origin=(11,0,0))
w1=cq.Workplane('ZX',origin=(0,-10,0))
r=w0.workplane(offset=4/2).moveTo(-10,20).cylinder(4,9).union(w0.sketch().arc((-90,-23),(-83,-27),(-80,-33)).arc((-81,-38),(-81,-44)).segment((-65,-44)).segment((-65,4)).arc((-37,20),(-47,45)).segment((-47,47)).segment((-50,47)).arc((-64,49),(-77,47)).segment((-90,47)).segment((-90,28)).arc((-100,12),(-90,-3)).close().assemble().reset().face(w0.sketch().segment((-90,4),(-90,24)).arc((-95,14),(-90,4)).assemble(),mode='s').push([(-77,42)]).circle(3,mode='s').finalize().extrude(45)).union(w0.workplane(offset=57/2).moveTo(64,-28).cylinder(57,36)).union(w1.sketch().push([(30,-27.5)]).rect(68,81).push([(30,-28)]).circle(20,mode='s').finalize().extrude(6))