import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,6,0))
r=w0.sketch().segment((47,-100),(80,-100)).segment((80,-81)).arc((89,-63),(80,-44)).segment((80,-25)).segment((47,-25)).segment((47,-44)).arc((38,-63),(47,-81)).close().assemble().finalize().extrude(-72).union(w0.workplane(offset=55/2).moveTo(64,97).cylinder(55,3)).union(w0.sketch().segment((-42,18),(-39,19)).segment((-35,10)).segment((-35,15)).segment((-12,15)).segment((-12,14)).segment((-7,30)).segment((-10,30)).segment((-10,31)).segment((-12,30)).segment((-35,30)).segment((-35,23)).arc((-88,9),(-35,-4)).segment((-35,-5)).segment((-32,-5)).close().assemble().reset().face(w0.sketch().segment((-17,37),(-12,36)).segment((-12,30)).segment((-10,30)).segment((-5,56)).segment((-13,57)).close().assemble()).finalize().extrude(60))