import cadquery as cq
w0=cq.Workplane('YZ',origin=(24,0,0))
r=w0.sketch().segment((26,-18),(39,-18)).arc((55,-10),(71,-18)).segment((84,-18)).segment((84,24)).arc((86,24),(88,25)).segment((84,31)).segment((84,33)).segment((85,33)).arc((62,38),(57,15)).arc((42,10),(31,-2)).segment((26,3)).close().assemble().push([(77,53)]).circle(23).finalize().extrude(-48).union(w0.sketch().segment((-100,3),(-79,3)).segment((-79,-75)).segment((10,-75)).segment((10,-42)).segment((84,-42)).segment((84,35)).segment((-5,35)).segment((-5,12)).segment((-79,12)).segment((-79,4)).segment((-100,4)).close().assemble().reset().face(w0.sketch().segment((-46,-34),(-31,-44)).segment((-21,-29)).segment((-36,-19)).close().assemble(),mode='s').push([(20,-13)]).circle(10,mode='s').finalize().extrude(-47))