import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-25))
r=w0.sketch().segment((-51,51),(-29,51)).segment((-30,100)).segment((-51,100)).close().assemble().finalize().extrude(27).union(w0.sketch().segment((-42,26),(-32,23)).segment((-24,44)).segment((-34,48)).close().assemble().finalize().extrude(45)).union(w0.sketch().segment((-42,4),(-41,4)).segment((-41,-36)).segment((-19,-36)).arc((-27,-68),(-6,-96)).segment((-6,-61)).segment((43,-61)).segment((43,-84)).arc((50,-51),(30,-25)).segment((30,-24)).segment((40,-24)).segment((40,-18)).segment((39,-18)).segment((39,4)).segment((40,4)).segment((40,8)).segment((39,8)).segment((39,42)).segment((-41,42)).segment((-41,8)).segment((-42,8)).close().assemble().push([(0,3)]).circle(10,mode='s').push([(5,40)]).circle(1,mode='s').reset().face(w0.sketch().segment((-6,-98),(-5,-98)).arc((11,-100),(26,-98)).segment((24,-98)).segment((-6,-96)).close().assemble()).finalize().extrude(50))