import cadquery as cq
w0=cq.Workplane('YZ',origin=(-18,0,0))
w1=cq.Workplane('ZX',origin=(0,53,0))
r=w0.sketch().segment((10,-26),(75,-47)).segment((83,-22)).segment((92,-22)).segment((92,-14)).segment((88,-14)).segment((100,-4)).segment((45,17)).segment((45,-14)).segment((10,-14)).close().assemble().finalize().extrude(53).union(w0.sketch().segment((-100,35),(-82,-47)).segment((-8,-30)).segment((-8,-43)).segment((-4,-43)).segment((-4,-54)).segment((28,-54)).segment((28,-43)).segment((31,-43)).segment((31,-21)).segment((85,-21)).segment((85,1)).segment((31,1)).segment((31,20)).segment((28,20)).segment((28,30)).segment((-4,30)).segment((-11,54)).close().assemble().push([(-46,4)]).circle(34,mode='s').finalize().extrude(105)).union(w1.sketch().push([(23.5,-82.5)]).rect(11,7).push([(23,-82)]).circle(2,mode='s').finalize().extrude(25))