import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,16))
w1=cq.Workplane('ZX',origin=(0,26,0))
r=w0.sketch().segment((-67,78),(-51,59)).arc((-59,33),(-39,14)).segment((-39,13)).segment((-38,13)).arc((-18,13),(-2,27)).segment((1,25)).segment((-29,83)).segment((-21,71)).segment((-55,51)).segment((-66,79)).close().assemble().reset().face(w0.sketch().segment((-46,-20),(-45,-21)).segment((-39,-17)).segment((-39,-16)).close().assemble()).reset().face(w0.sketch().segment((-36,19),(-31,7)).segment((-2,20)).segment((-18,40)).segment((-1,33)).segment((1,37)).segment((-11,43)).arc((-19,20),(-36,19)).assemble()).push([(9,-3)]).circle(16).finalize().extrude(-68).union(w0.workplane(offset=-9/2).moveTo(42,-66).box(2,68,9)).union(w0.workplane(offset=36/2).moveTo(-23,28).cylinder(36,29)).union(w1.sketch().segment((-40,-38),(-1,-38)).segment((-1,-33)).segment((36,-33)).segment((36,67)).segment((-40,67)).segment((-40,-7)).segment((-40,-15)).close().assemble().finalize().extrude(-52))