import cadquery as cq
w0=cq.Workplane('YZ',origin=(25,0,0))
r=w0.sketch().segment((-25,-64),(4,-64)).segment((4,-100)).segment((11,-100)).segment((11,-64)).segment((40,-64)).segment((40,-32)).segment((11,-32)).segment((11,-13)).segment((80,-13)).segment((80,31)).segment((22,31)).segment((22,34)).segment((41,51)).segment((31,65)).segment((22,59)).segment((22,64)).segment((19,64)).segment((19,68)).segment((15,68)).segment((15,64)).segment((14,64)).arc((-79,54),(-3,0)).segment((4,-3)).segment((4,-32)).segment((-25,-32)).close().assemble().finalize().extrude(-67).union(w0.sketch().segment((-37,81),(-10,56)).segment((-10,54)).segment((-8,54)).segment((30,24)).segment((66,60)).segment((40,85)).segment((40,87)).segment((38,87)).segment((15,100)).segment((15,87)).segment((-10,87)).segment((-10,64)).segment((-32,84)).close().assemble().finalize().extrude(18))