import cadquery as cq
w0=cq.Workplane('YZ',origin=(-28,0,0))
r=w0.sketch().segment((11,5),(16,-3)).segment((30,6)).segment((25,12)).close().assemble().finalize().extrude(9).union(w0.sketch().segment((-100,-33),(-80,-33)).arc((-65,-39),(-50,-33)).segment((-30,-33)).segment((-30,1)).segment((-50,1)).arc((-65,7),(-80,1)).segment((-100,1)).close().assemble().reset().face(w0.sketch().arc((28,5),(34,4),(39,4)).segment((40,4)).segment((44,6)).arc((48,16),(56,22)).segment((56,37)).segment((70,37)).segment((70,23)).arc((80,16),(86,4)).segment((97,4)).segment((97,2)).segment((100,5)).segment((97,7)).arc((62,39),(30,11)).segment((28,10)).close().assemble()).finalize().extrude(25)).union(w0.workplane(offset=56/2).moveTo(72,-33).cylinder(56,5))