import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,7,0))
r=w0.sketch().segment((12,25),(12,74)).segment((66,74)).segment((66,75)).arc((71,75),(66,76)).segment((66,78)).arc((-76,-65),(92,40)).segment((92,25)).segment((66,25)).segment((66,23)).segment((16,21)).segment((16,25)).close().assemble().reset().face(w0.sketch().segment((-19,-70),(-4,-70)).arc((3,-79),(12,-86)).segment((12,-88)).segment((16,-88)).segment((16,-89)).segment((27,-89)).segment((27,-94)).segment((33,-94)).segment((33,-89)).segment((44,-89)).segment((44,-88)).segment((49,-88)).segment((49,-86)).arc((58,-79),(66,-70)).segment((81,-70)).segment((81,-36)).segment((66,-36)).arc((58,-27),(49,-20)).segment((49,-18)).segment((44,-18)).segment((44,-15)).segment((33,-15)).segment((33,-10)).segment((27,-10)).segment((27,-15)).segment((16,-15)).segment((16,-18)).segment((12,-18)).segment((12,-15)).segment((10,-15)).segment((10,-18)).segment((-19,-18)).close().assemble(),mode='s').finalize().extrude(-14)