import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,49))
r=w0.sketch().segment((-11,86),(-7,-12)).segment((28,-10)).segment((28,-22)).segment((32,-22)).segment((32,-10)).segment((71,-8)).segment((66,90)).segment((32,88)).segment((32,100)).segment((28,100)).segment((28,88)).close().assemble().reset().face(w0.sketch().segment((28,19),(28,59)).arc((10,39),(28,19)).assemble(),mode='s').reset().face(w0.sketch().arc((32,19),(50,39),(32,59)).close().assemble(),mode='s').finalize().extrude(-98).union(w0.sketch().push([(-14,-43)]).circle(57).reset().face(w0.sketch().segment((-70,-43),(-58,-43)).arc((-58,-54),(-53,-64)).segment((-53,-81)).segment((-29,-81)).segment((-29,-64)).arc((-25,-54),(-25,-43)).segment((-12,-43)).segment((-12,-40)).segment((-26,-40)).arc((-27,-39),(-29,-38)).segment((-29,-21)).segment((-53,-21)).segment((-53,-38)).arc((-55,-39),(-56,-40)).segment((-70,-40)).close().assemble(),mode='s').finalize().extrude(-41))