import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,-39,0))
r=w0.sketch().segment((-70,-100),(-28,-100)).segment((-28,-77)).arc((-19,-56),(-28,-35)).segment((-28,-11)).segment((-70,-11)).segment((-70,-35)).arc((-79,-56),(-70,-77)).close().assemble().reset().face(w0.sketch().segment((-32,34),(20,14)).segment((30,39)).segment((32,34)).segment((39,40)).segment((33,48)).segment((45,80)).segment((-7,100)).segment((-17,75)).segment((-19,81)).segment((-27,75)).segment((-21,67)).close().assemble()).finalize().extrude(58).union(w0.sketch().push([(53,-12)]).circle(26).push([(56,-28)]).circle(5,mode='s').finalize().extrude(78))