import cadquery as cq
w0=cq.Workplane('YZ',origin=(61,0,0))
r=w0.sketch().arc((79,-17),(81,0),(79,17)).close().assemble().finalize().extrude(-161).union(w0.sketch().segment((-81,28),(-74,-40)).segment((-43,-38)).segment((-59,-62)).segment((-16,-82)).segment((-4,-57)).segment((35,-53)).segment((32,-21)).segment((63,-21)).segment((63,-18)).segment((31,-18)).segment((30,-15)).segment((69,-15)).segment((66,40)).segment((35,38)).segment((51,62)).segment((8,82)).segment((-4,57)).segment((-44,53)).segment((-41,21)).close().assemble().finalize().extrude(37)).union(w0.sketch().segment((-42,-67),(34,-67)).segment((34,-31)).segment((40,-31)).segment((40,31)).segment((34,31)).segment((34,67)).segment((-42,67)).segment((-42,31)).segment((-42,-31)).close().assemble().finalize().extrude(39))