import cadquery as cq
w0=cq.Workplane('YZ',origin=(53,0,0))
r=w0.sketch().segment((-4,-8),(2,-91)).segment((100,-82)).segment((92,1)).close().assemble().finalize().extrude(-107).union(w0.sketch().segment((-100,2),(-61,-48)).segment((-61,-64)).segment((-47,-64)).segment((-41,-72)).segment((-32,-64)).segment((60,-64)).segment((60,91)).segment((-61,91)).segment((-61,39)).segment((-84,16)).segment((-61,49)).segment((-61,-17)).segment((-75,-16)).segment((-75,34)).segment((-78,30)).segment((-84,15)).segment((-87,16)).close().assemble().reset().face(w0.sketch().segment((-30,40),(-24,12)).segment((11,15)).segment((8,40)).close().assemble(),mode='s').finalize().extrude(-77))