import cadquery as cq
w0=cq.Workplane('YZ',origin=(-43,0,0))
r=w0.sketch().push([(-48,-65)]).circle(30).push([(-47,-93)]).rect(2,2,mode='s').finalize().extrude(-9).union(w0.sketch().segment((-19,94),(-7,33)).arc((-8,19),(-2,6)).segment((9,-34)).segment((10,-34)).segment((10,-25)).segment((91,-33)).segment((100,52)).segment((39,58)).arc((22,61),(6,62)).segment((-7,64)).segment((-13,95)).close().assemble().finalize().extrude(26)).union(w0.sketch().segment((-100,-7),(-98,-7)).segment((-98,-18)).segment((-69,-18)).segment((-69,-24)).segment((-37,-24)).segment((-37,-34)).segment((10,-34)).segment((10,-24)).segment((38,-24)).segment((38,-1)).segment((10,-1)).segment((10,9)).segment((-21,9)).segment((-21,14)).segment((-24,14)).segment((-24,22)).segment((-98,22)).segment((-98,11)).segment((-100,11)).close().assemble().finalize().extrude(94))