import cadquery as cq
w0=cq.Workplane('YZ',origin=(-4,0,0))
r=w0.sketch().segment((-65,-75),(32,-75)).segment((32,20)).segment((28,20)).segment((44,50)).segment((-38,100)).segment((-60,63)).segment((6,20)).segment((-65,20)).close().assemble().push([(-16.5,-27)]).rect(55,84,mode='s').finalize().extrude(-31).union(w0.workplane(offset=4/2).moveTo(15,-64).box(100,72,4)).union(w0.sketch().segment((-58,-44),(-53,-50)).segment((-11,-27)).segment((8,-52)).segment((23,-40)).segment((9,-24)).segment((23,-12)).segment((18,-6)).segment((2,-17)).segment((-10,-17)).segment((-10,-21)).close().assemble().finalize().extrude(39))