import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,-34,0))
r=w0.sketch().segment((-49,-10),(-42,-15)).arc((-26,-37),(-2,-45)).segment((6,-50)).segment((11,-43)).arc((34,-29),(43,-3)).segment((49,5)).segment((42,11)).arc((26,37),(2,46)).segment((-6,50)).segment((-11,44)).arc((-34,31),(-43,3)).close().assemble().push([(2,18)]).circle(20,mode='s').push([(33,-7)]).circle(5,mode='s').finalize().extrude(-66).union(w0.workplane(offset=-22/2).box(108,152,22)).union(w0.sketch().circle(75).reset().face(w0.sketch().segment((-58,-31),(58,-31)).segment((58,31)).segment((-58,31)).segment((-58,17)).arc((-61,11),(-58,5)).close().assemble(),mode='s').push([(0,-56)]).circle(17,mode='s').reset().face(w0.sketch().segment((-17,47),(-11,47)).arc((0,43),(11,47)).segment((17,47)).segment((17,57)).segment((11,57)).arc((0,61),(-11,57)).segment((-17,57)).close().assemble(),mode='s').finalize().extrude(134))