import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,-41,0))
r=w0.sketch().arc((-73,-10),(-64,-13),(-56,-13)).segment((-57,-12)).segment((-45,7)).segment((-43,6)).segment((-44,5)).segment((-41,5)).segment((-41,7)).arc((-33,9),(-25,13)).segment((-25,14)).arc((-33,16),(-41,17)).segment((-41,18)).segment((-44,18)).segment((-44,17)).arc((-47,16),(-50,14)).segment((-50,13)).arc((-61,10),(-70,3)).segment((-57,-9)).segment((-67,-20)).close().assemble().finalize().extrude(6).union(w0.workplane(offset=6/2).moveTo(-40.5,54).box(11,92,6)).union(w0.sketch().push([(23,43)]).circle(20).reset().face(w0.sketch().segment((10,-91),(25,-91)).segment((25,-100)).segment((58,-100)).segment((58,-91)).segment((73,-91)).segment((73,-30)).segment((58,-30)).segment((58,-21)).segment((25,-21)).segment((25,-30)).segment((10,-30)).close().assemble()).finalize().extrude(82))