import cadquery as cq
w0=cq.Workplane('ZX',origin=(0,-61,0))
r=w0.sketch().push([(-17,-24)]).circle(71).reset().face(w0.sketch().segment((-46,-12),(-18,-59)).segment((-13,-55)).arc((-14,-52),(-13,-50)).segment((-24,-35)).segment((19,-35)).segment((19,16)).segment((-28,16)).segment((-28,-21)).segment((-38,-6)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-12,-73),(35,-73)).segment((35,-42)).segment((39,-46)).segment((46,-41)).segment((19,4)).segment((19,-35)).segment((-12,-35)).close().assemble(),mode='s').finalize().extrude(99).union(w0.sketch().segment((-100,-7),(-29,-7)).arc((100,24),(-30,38)).segment((-100,38)).close().assemble().reset().face(w0.sketch().segment((-46,-12),(-30,-12)).arc((-35,0),(-36,14)).segment((-46,14)).close().assemble(),mode='s').finalize().extrude(122))