import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,21))
r=w0.sketch().segment((-76,74),(-69,74)).arc((-65,65),(-57,58)).arc((-56,55),(-54,52)).segment((-54,32)).segment((-17,32)).segment((-17,13)).segment((52,13)).segment((52,31)).segment((11,31)).segment((11,80)).segment((-2,80)).segment((-2,82)).segment((52,80)).segment((51,89)).segment((-24,89)).segment((-24,85)).arc((-49,100),(-69,78)).segment((-76,78)).close().assemble().reset().face(w0.sketch().segment((-17,25),(-17,31)).segment((-13,31)).arc((-16,29),(-17,25)).assemble(),mode='s').finalize().extrude(-43).union(w0.sketch().segment((-42,-51),(47,-51)).segment((47,-30)).segment((48,-30)).segment((49,-5)).segment((51,6)).segment((50,6)).segment((53,31)).segment((28,34)).segment((27,34)).segment((27,35)).segment((26,34)).segment((-14,36)).segment((-14,16)).segment((-26,16)).segment((-26,6)).segment((-42,6)).close().assemble().finalize().extrude(-32)).union(w0.workplane(offset=-24/2).moveTo(44,-67).cylinder(24,32))