import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-36))
r=w0.sketch().arc((-50,31),(-49,-7),(-18,10)).segment((42,10)).segment((42,100)).segment((-50,100)).close().assemble().push([(-39,13)]).circle(14,mode='s').finalize().extrude(-32).union(w0.sketch().segment((-20,-74),(-16,-74)).arc((-11,-80),(-4,-85)).segment((-4,-100)).segment((35,-100)).segment((35,-85)).arc((42,-80),(47,-74)).segment((51,-74)).segment((51,-71)).arc((61,-49),(51,-26)).segment((51,-24)).segment((47,-24)).arc((42,-19),(35,-14)).segment((35,1)).segment((-4,1)).segment((-4,-14)).arc((-11,-19),(-16,-24)).segment((-20,-24)).segment((-20,-26)).arc((-22,-49),(-20,-71)).close().assemble().push([(1,-49)]).rect(2,56,mode='s').push([(40,-49)]).rect(2,56,mode='s').finalize().extrude(8)).union(w0.workplane(offset=104/2).moveTo(37.5,-11.5).box(3,83,104))