import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,21))
w1=cq.Workplane('XY',origin=(0,0,22))
r=w0.sketch().segment((-76,77),(-68,77)).arc((-65,65),(-54,55)).segment((-54,32)).segment((-17,32)).segment((-17,13)).segment((52,13)).segment((53,31)).segment((-5,33)).segment((-5,32)).segment((11,32)).segment((11,81)).segment((-23,81)).arc((-24,84),(-25,86)).segment((-25,93)).segment((-32,93)).arc((-49,100),(-66,89)).segment((-67,89)).segment((-68,84)).arc((-69,81),(-69,78)).segment((-76,79)).close().assemble().push([(38,84.5)]).rect(26,9).finalize().extrude(-42).union(w0.sketch().segment((-42,-51),(28,-51)).segment((28,-46)).segment((43,-45)).segment((42,-32)).segment((48,-32)).segment((48,-6)).segment((41,-6)).segment((40,33)).segment((-17,30)).segment((-17,24)).segment((-20,24)).segment((-20,21)).segment((-21,21)).segment((-21,16)).segment((-42,6)).close().assemble().finalize().extrude(-31)).union(w1.sketch().segment((-40,32),(12,32)).segment((12,81)).segment((-23,81)).arc((-20,50),(-40,29)).close().assemble().push([(44,-68)]).circle(32).finalize().extrude(-24))