import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-19))
r=w0.sketch().push([(-84.5,54.5)]).rect(31,83).push([(-8,-28.5)]).rect(26,7).push([(-8,-29)]).circle(3,mode='s').finalize().extrude(-24).union(w0.sketch().segment((-34,-75),(-21,-75)).arc((-9,-78),(3,-75)).segment((16,-75)).segment((16,-69)).arc((26,-54),(29,-36)).arc((33,-35),(37,-35)).segment((37,-18)).segment((47,-18)).arc((36,1),(16,9)).segment((16,19)).segment((3,19)).arc((-9,22),(-21,19)).segment((-34,19)).segment((-34,9)).arc((-57,-28),(-34,-69)).close().assemble().reset().face(w0.sketch().segment((37,-69),(47,-69)).segment((47,-96)).segment((100,-96)).segment((100,-84)).arc((71,-77),(47,-60)).segment((47,-67)).segment((37,-67)).close().assemble()).finalize().extrude(2)).union(w0.workplane(offset=62/2).moveTo(55.5,56.5).box(49,33,62))