import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-7))
r=w0.sketch().arc((-6,-81),(33,-99),(75,-86)).arc((46,24),(-6,-81)).assemble().reset().face(w0.sketch().arc((22,-71),(29,-85),(44,-78)).segment((75,-78)).segment((75,-2)).segment((27,-3)).segment((28,-23)).arc((7,-43),(22,-69)).close().assemble(),mode='s').finalize().extrude(-81).union(w0.sketch().segment((-100,74),(-92,67)).segment((-92,22)).segment((23,22)).segment((23,99)).segment((-86,99)).segment((-86,94)).segment((-92,94)).segment((-92,89)).arc((-94,85),(-96,82)).close().assemble().reset().face(w0.sketch().segment((-51,27),(-41,27)).segment((-41,26)).segment((-34,26)).segment((-34,27)).segment((-24,27)).segment((-24,33)).arc((-1,63),(-24,94)).segment((-24,99)).segment((-34,99)).segment((-34,100)).segment((-41,100)).segment((-41,99)).segment((-51,99)).segment((-51,94)).arc((-69,63),(-51,33)).close().assemble(),mode='s').finalize().extrude(95))