import cadquery as cq
w0=cq.Workplane('YZ',origin=(-32,0,0))
r=w0.sketch().segment((-91,-52),(-72,-47)).segment((-69,-41)).segment((-63,-45)).segment((30,-16)).arc((40,76),(-50,51)).segment((-51,52)).segment((-51,50)).arc((-49,43),(-49,35)).segment((-76,25)).segment((-88,25)).arc((-89,36),(-88,46)).segment((-91,46)).segment((-91,48)).arc((-100,-10),(-78,-54)).segment((-91,-50)).close().assemble().finalize().extrude(19).union(w0.sketch().segment((-64,76),(-22,6)).segment((-18,8)).segment((-60,78)).close().assemble().reset().face(w0.sketch().segment((21,-8),(35,4)).arc((27,1),(21,-2)).close().assemble()).reset().face(w0.sketch().segment((33,-84),(36,-84)).arc((67,-85),(90,-64)).segment((93,-63)).segment((92,-62)).arc((100,-38),(94,-15)).segment((94,-14)).segment((93,-14)).arc((63,-13),(40,-34)).segment((37,-36)).segment((38,-37)).arc((33,-60),(41,-82)).close().assemble()).finalize().extrude(65))