import cadquery as cq
w0=cq.Workplane('YZ',origin=(-49,0,0))
r=w0.sketch().segment((-88,70),(-73,57)).segment((-73,58)).segment((-48,43)).arc((-40,38),(-32,34)).segment((-1,19)).segment((17,56)).segment((-14,68)).arc((-22,72),(-30,75)).segment((-67,100)).close().assemble().reset().face(w0.sketch().segment((-53,-100),(-36,-100)).segment((-36,-73)).arc((-27,-56),(-36,-39)).segment((-36,-12)).segment((-53,-12)).segment((-53,-39)).arc((-62,-56),(-53,-73)).close().assemble()).finalize().extrude(43).union(w0.sketch().segment((16,-11),(41,-11)).segment((41,-50)).segment((62,-50)).segment((62,-11)).segment((88,-11)).segment((88,82)).segment((16,82)).close().assemble().reset().face(w0.sketch().segment((20,4),(23,-2)).segment((36,3)).segment((33,11)).close().assemble(),mode='s').finalize().extrude(98))