import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,29))
r=w0.sketch().segment((-6,-7),(31,-7)).segment((31,12)).arc((35,24),(31,36)).segment((31,55)).segment((-6,55)).segment((-6,36)).arc((-10,24),(-6,12)).close().assemble().push([(11,98)]).circle(2).finalize().extrude(-58).union(w0.sketch().push([(-19.5,-73)]).rect(31,54).reset().face(w0.sketch().segment((-26,-80),(-21,-80)).arc((-25,-71),(-21,-61)).segment((-26,-61)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-21,-84),(-9,-84)).segment((-9,-65)).segment((-12,-65)).arc((-16,-58),(-20,-65)).segment((-21,-65)).close().assemble(),mode='s').finalize().extrude(-57))