import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,28))
r=w0.sketch().push([(-10.5,-30)]).rect(89,56).reset().face(w0.sketch().segment((-54,-24),(-50,-37)).segment((-28,-29)).segment((-31,-20)).segment((15,-8)).segment((14,-6)).segment((-31,-21)).segment((-32,-17)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-29,-27),(-27,-34)).segment((-21,-32)).close().assemble(),mode='s').reset().face(w0.sketch().segment((3,-48),(12,-50)).segment((14,-40)).segment((11,-41)).segment((10,-44)).close().assemble(),mode='s').finalize().extrude(-128).union(w0.sketch().segment((-62,-14),(-54,-14)).arc((0,-54),(54,-14)).segment((62,-14)).segment((62,17)).segment((54,17)).arc((0,58),(-54,17)).segment((-62,17)).close().assemble().push([(0,2)]).rect(58,78,mode='s').finalize().extrude(72))