import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-46))
w1=cq.Workplane('ZX',origin=(0,-12,0))
r=w0.sketch().segment((-100,-53),(-98,-54)).segment((-98,-51)).segment((-93,-51)).segment((-93,-73)).segment((-90,-74)).segment((-82,-56)).arc((-83,-50),(-81,-43)).segment((-85,-41)).segment((-82,-37)).segment((-78,-38)).arc((-70,-29),(-69,-17)).segment((-68,-13)).segment((-69,-13)).arc((-70,-12),(-72,-12)).segment((-77,-9)).segment((-85,-1)).segment((-93,-16)).arc((-96,-16),(-98,-17)).segment((-98,-27)).segment((-93,-27)).segment((-93,-49)).segment((-96,-49)).close().assemble().reset().face(w0.sketch().segment((-98,-17),(-98,39)).arc((-100,11),(-98,-17)).assemble()).reset().face(w0.sketch().segment((-97,46),(-74,46)).segment((-74,74)).segment((-98,74)).segment((-98,47)).arc((-98,46),(-97,46)).assemble()).finalize().extrude(92).union(w1.sketch().push([(-21.5,64)]).rect(37,72).push([(-34,82)]).circle(6,mode='s').push([(-22,64)]).circle(9,mode='s').push([(-17.5,30.5)]).rect(25,5,mode='s').finalize().extrude(66))