import cadquery as cq
w0=cq.Workplane('YZ',origin=(52,0,0))
r=w0.sketch().segment((-96,45),(-92,40)).segment((-87,45)).close().assemble().reset().face(w0.sketch().segment((-59,44),(-55,44)).segment((-55,-4)).segment((44,-4)).segment((44,44)).segment((56,44)).segment((56,100)).segment((-59,100)).close().assemble()).reset().face(w0.sketch().segment((-7,69),(5,69)).segment((4,74)).close().assemble(),mode='s').finalize().extrude(-104).union(w0.sketch().segment((-45,-80),(-1,-81)).arc((36,-100),(74,-87)).segment((77,-87)).segment((77,-82)).arc((82,-73),(86,-64)).segment((91,-68)).segment((96,-21)).segment((91,-20)).arc((44,14),(-5,-7)).segment((-10,-6)).segment((-15,-41)).arc((-18,-47),(-20,-54)).segment((-21,-61)).arc((-29,-69),(-36,-80)).close().assemble().finalize().extrude(-8))