import cadquery as cq
w0=cq.Workplane('YZ',origin=(31,0,0))
r=w0.workplane(offset=-62/2).moveTo(-5,-16).box(128,26,62).union(w0.sketch().arc((-57,15),(-39,-68),(43,-55)).segment((50,-55)).segment((50,-54)).segment((53,-54)).segment((53,-55)).segment((62,-52)).segment((62,-51)).arc((65,-51),(68,-50)).segment((69,-52)).segment((98,-46)).segment((97,-43)).arc((99,-39),(100,-34)).segment((59,-41)).segment((59,-3)).arc((20,41),(-38,35)).arc((-92,67),(-57,15)).assemble().reset().face(w0.sketch().arc((-43,-30),(-8,-53),(35,-39)).arc((25,-36),(17,-31)).segment((-41,-23)).segment((-41,-30)).close().assemble(),mode='s').reset().face(w0.sketch().arc((-43,-2),(3,-30),(36,11)).arc((28,11),(20,18)).arc((-10,25),(-38,8)).segment((-38,10)).arc((-41,4),(-43,-2)).assemble(),mode='s').finalize().extrude(-58))