import cadquery as cq
w0=cq.Workplane('YZ',origin=(-3,0,0))
r=w0.sketch().segment((-61,30),(-44,30)).arc((-32,7),(-11,-7)).arc((-2,-9),(7,-8)).arc((41,10),(51,48)).segment((51,50)).segment((50,50)).arc((3,88),(-44,50)).segment((-45,50)).segment((-45,48)).arc((-46,46),(-46,44)).arc((-50,40),(-52,36)).segment((-61,36)).close().assemble().finalize().extrude(-97).union(w0.sketch().segment((22,-35),(30,-35)).segment((30,51)).segment((22,51)).segment((22,18)).arc((24,16),(22,14)).close().assemble().finalize().extrude(-11)).union(w0.sketch().segment((-34,-65),(-24,-65)).segment((-24,-88)).segment((51,-88)).segment((51,-65)).segment((61,-65)).segment((61,28)).segment((51,28)).segment((51,50)).segment((-24,50)).segment((-24,28)).segment((-34,28)).close().assemble().finalize().extrude(103))