import cadquery as cq
w0=cq.Workplane('XY',origin=(0,0,-8))
r=w0.workplane(offset=-92/2).moveTo(-18.5,-10.5).box(163,59,92).union(w0.sketch().segment((-53,54),(-52,54)).segment((-52,48)).segment((72,48)).segment((72,94)).segment((-52,94)).segment((-52,61)).segment((-53,61)).close().assemble().reset().face(w0.sketch().segment((-48,-86),(1,-94)).segment((11,-48)).arc((54,-47),(85,-22)).segment((100,-12)).segment((90,3)).arc((86,12),(81,20)).segment((72,35)).segment((67,32)).segment((71,32)).segment((71,12)).segment((-39,12)).segment((-39,32)).segment((-27,32)).close().assemble()).finalize().extrude(-13)).union(w0.sketch().segment((-48,-86),(-4,-91)).segment((11,65)).segment((-33,69)).segment((-41,-22)).segment((-42,-22)).segment((-42,-32)).close().assemble().finalize().extrude(108))