import cadquery as cq
w0=cq.Workplane('YZ',origin=(-21,0,0))
r=w0.sketch().segment((-86,-14),(-58,-44)).arc((-41,-90),(6,-72)).segment((5,-74)).segment((5,-43)).segment((38,-43)).segment((38,15)).segment((22,15)).segment((2,23)).segment((-1,15)).segment((-1,11)).segment((-3,11)).segment((-1,9)).segment((-1,-13)).arc((-18,-1),(-41,-1)).segment((-50,18)).close().assemble().reset().face(w0.sketch().segment((-47,-35),(-30,-39)).segment((-28,-30)).segment((-45,-26)).close().assemble(),mode='s').reset().face(w0.sketch().segment((-34,66),(34,57)).segment((37,91)).segment((-30,100)).close().assemble()).finalize().extrude(28).union(w0.sketch().segment((-40,-17),(-3,-55)).arc((1,-73),(17,-84)).arc((33,-100),(49,-80)).segment((86,-53)).segment((56,-9)).segment((38,-20)).segment((51,-10)).segment((55,-14)).arc((51,-13),(47,-13)).segment((47,-16)).segment((46,-16)).segment((-1,-49)).segment((-4,-45)).segment((31,-16)).segment((13,-16)).segment((13,-15)).arc((10,-14),(7,-14)).segment((13,-29)).segment((-34,-4)).close().assemble().finalize().extrude(42))